# render.yaml (if Backend is root)
services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 90 --workers 2
    envVars:
      - key: PORT
        value: 10000
