services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    workingDir: Backend
    envVars:
      - key: PORT
        value: 10000  # or leave unset (Render assigns automatically)
